name: aiaugmentationENV
channels:
  - defaults
dependencies:
  - importlib-metadata==6.0.0
  - pycparser==2.21
  - certifi
  - aiohttp==3.8.3
  - grpc-cpp==1.48.2
  - huggingface_hub
  - cryptography==39.0.1
  - xxhash==0.8.0
  - libboost==1.73.0
  - typing_extensions==4.6.3
  - intel-openmp==2023.1.0
  - dill==0.3.6
  - mkl-service==2.4.0
  - sqlite==3.41.2
  - numexpr==2.8.4
  - urllib3==1.26.16
  - python-dateutil==2.8.2
  - re2==2022.04.01
  - regex==2022.7.9
  - zipp==3.11.0
  - aws-c-event-stream==0.1.6
  - six==1.16.0
  - tbb==2021.8.0
  - click==8.0.4
  - pyarrow==11.0.0
  - zlib==1.2.13
  - win_inet_pton==1.1.0
  - arrow-cpp==11.0.0
  - aws-sdk-cpp==1.8.185
  - bzip2==1.0.8
  - blas==1.0=mkl
  - async-timeout==4.0.2
  - libevent==2.1.12
  - multiprocess==0.70.14
  - gflags==2.2.2
  - colorama==0.4.6
  - bottleneck==1.3.5
  - fsspec==2023.4.0
  - aws-c-common==0.6.8
  - numpy-base==1.25.0
  - libbrotlidec==1.0.9
  - pyyaml==6.0
  - utf8proc==2.6.1
  - c-ares==1.19.0
  - pyopenssl==23.0.0
  - orc==1.7.4
  - xz==5.4.2
  - openssl
  - boost-cpp==1.73.0
  - libssh2==1.10.0
  - libcurl==8.1.1
  - attrs==22.1.0
  - lz4-c==1.9.4
  - dataclasses==0.8
  - sacremoses
  - yarl==1.8.1
  - libprotobuf==3.20.3
  - requests==2.29.0
  - protobuf==3.20.3
  - tokenizers
  - frozenlist==1.3.3
  - aws-checksums==0.1.11
  - snappy==1.1.9
  - transformers
  - python==3.9.17
  - charset-normalizer==2.0.4
  - numpy==1.25.0
  - brotlipy==0.7.0
  - glog==0.5.0
  - yaml==0.2.5
  - tqdm==4.65.0
  - tzdata==2023c
  - multidict==6.0.2
  - pysocks==1.7.1
  - datasets
  - aiosignal==1.2.0
  - packaging==23.0
  - abseil-cpp==20211102.0
  - vc==14.2
  - libthrift==0.15.0
  - wheel==0.38.4
  - cffi==1.15.1
  - zstd==1.5.5
  - ca-certificates
  - pip==23.1.2
  - responses==0.13.3
  - setuptools==67.8.0
  - idna==3.4
  - importlib_metadata
  - pandas==1.5.3
  - libbrotlicommon==1.0.9
  - libbrotlienc==1.0.9
  - python-xxhash==2.0.2
  - mkl_random==1.2.2
  - pytz==2022.7
  - joblib==1.2.0
  - seaborn
  - evaluate
  - sacrebleu
  - nltk
  - spacy
  - openpyxl
  - sentencepiece
  - pylev
  - language_tool_python
  - tabulate
  - lxml
